trigger:
- main
- dev

pool:
  vmImage: 'ubuntu-latest' # 使用最新的 Ubuntu 镜像

variables:
- group: GitHubSyncCredentials # 替换成你的 Variable Group 名称

steps:
- script: |
    git config --global user.email "void@tao"
    git config --global user.name "Azure Pipeline Sync"

    git remote add github https://$(GitHubPAT)@github.com/voidtao/qbitrace.git

    echo "Fetching all branches and tags from origin (Azure DevOps)..."
    git fetch origin --prune
    echo "Syncing to GitHub..."
    git push --force github main

    git push --force github dev

  displayName: 'Sync Azure Repo to GitHub'
  env:
    GitHubPAT: $(GitHubPAT)