trigger:
- main
- dev

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: GitHubSyncCredentials

steps:
- checkout: self
  persistCredentials: true  # 保留认证信息
  fetchDepth: 0  # 获取完整历史（所有分支）

- script: |
    git config --global user.email "void@tao"
    git config --global user.name "Azure Pipeline Sync"

    # 添加 GitHub 远程仓库
    git remote add github https://$(GitHubPAT)@github.com/voidtao/qbitrace.git

    # 列出所有分支（用于调试）
    echo "当前可用分支："
    git branch -a

    # 确保我们有要同步的分支，尝试同步 main 分支
    if git show-ref --verify --quiet refs/heads/main; then
      echo "正在同步 main 分支到 GitHub..."
      git push --force github refs/heads/main:refs/heads/main
    else
      echo "警告: 本地找不到 main 分支"
    fi

    # 尝试同步 dev 分支
    if git show-ref --verify --quiet refs/heads/dev; then
      echo "正在同步 dev 分支到 GitHub..."
      git push --force github refs/heads/dev:refs/heads/dev
    else
      echo "警告: 本地找不到 dev 分支"
    fi

  displayName: 'Sync Azure Repo to GitHub'
  env:
    GitHubPAT: $(GitHubPAT)