trigger:
- main
- dev

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: GitHubSyncCredentials

steps:
- checkout: self       # self 表示检出当前 Pipeline 所在的仓库
  persistCredentials: true # 非常重要：让后续脚本能使用内置认证信息
  fetchDepth: 0        # 推荐：获取所有历史记录和分支，可能使后续 fetch 非必需
  fetchTags: true      # 获取标签

- script: |
    git config --global user.email "void@tao"
    git config --global user.name "Azure Pipeline Sync"

    # 添加 GitHub 远程仓库
    git remote add github https://$(GitHubPAT)@github.com/voidtao/qbitrace.git

    echo "Fetching all branches and tags from origin (Azure DevOps)..."
    git fetch origin --prune

    echo "Syncing specified branches to GitHub..."
    git push --force github main
    git push --force github dev

  displayName: 'Sync Azure Repo to GitHub'
  env:
    GitHubPAT: $(GitHubPAT)