name: Docker Image CI

on:
  push:
    branches: [ stable ] 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Build the Docker image
      run: docker buildx build --platform linux/amd64,linux/arm64 --tag taovoid/qbitrace:latest --push \
           --build-arg PAT=${{ secrets.PERSONAL_ACCESS_TOKEN }} .