name: Docker Image CI

on:
  push:
    branches: [ dev ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Get version from package.json
      id: package-version
      run: echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
      
    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: taovoid/qbitrace:dev
        platforms: linux/amd64,linux/arm64
        build-args: PAT=${{ secrets.PERSONAL_ACCESS_TOKEN }}