name: Docker Image CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2 # 添加 setup-buildx-action
    - name: Build and push Docker image
      uses: docker/build-push-action@v3 # 使用 build-push-action 简化构建和推送步骤
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: taovoid/qbitrace:latest
        platforms: linux/amd64,linux/arm64,linux/s390x
        build-args: PAT=${{ secrets.PERSONAL_ACCESS_TOKEN }}